# Explore

In [1]:
%load_ext autoreload
%autoreload 2

## import packages

In [2]:
import sys
sys.path.append('..')

In [3]:
from source.data.mediasportif import get_matchs_data_from_url

## Scrap french ratings 2018 - 2022

In [4]:
url = "https://www.mediasportif.fr/2018/06/15/coupe-du-monde-2018-toutes-les-audiences-de-la-competition-en-france/"
game_ratings_2018_df = get_matchs_data_from_url(url)

In [5]:
url = "https://www.mediasportif.fr/2022/11/21/30655/"
game_ratings_2022_df = get_matchs_data_from_url(url)

## All games

In [6]:
game_ratings_2018_df

,date,day_of_week,day,month,year,game_type,hour,team_1,team_2,ratings
0,2018-06-14,JEUDI,14,JUIN,2018,POULE,17h,Russie,Arabie Saoudite,3980000
1,2018-06-15,VENDREDI,15,JUIN,2018,POULE,20h,Portugal,Espagne,8161000
2,2018-06-16,SAMEDI,16,JUIN,2018,POULE,12h,France,Australie,12590000
3,2018-06-16,SAMEDI,16,JUIN,2018,POULE,21h,Croatie,Nigeria,4054000
4,2018-06-17,DIMANCHE,17,JUIN,2018,POULE,17h,Allemagne,Mexique,5000000
5,2018-06-17,DIMANCHE,17,JUIN,2018,POULE,20h,Brésil,Suisse,8191000
6,2018-06-18,LUNDI,18,JUIN,2018,POULE,20h,Tunisie,Angleterre,7012000
7,2018-06-20,MERCREDI,20,JUIN,2018,POULE,20h,Iran,Espagne,1321000
8,2018-06-21,JEUDI,21,JUIN,2018,POULE,17h,France,Pérou,10720000
9,2018-06-21,JEUDI,21,JUIN,2018,POULE,20h,Argentine,Croatie,5969000
10,2018-06-23,SAMEDI,23,JUIN,2018,POULE,20h,Allemagne,Suède,6772000
11,2018-06-24,DIMANCHE,24,JUIN,2018,POULE,20h,Pologne,Colombie,6630000
12,2018-06-25,LUNDI,25,JUIN,2018,POULE,20h,Iran,Portugal,6760000
13,2018-06-26,MARDI,26,JUIN,2018,POULE,16h,Danemark,France,8670000
14,2018-06-26,MARDI,26,JUIN,2018,POULE,20h,Nigeria,Argentine,6572000
15,2018-06-27,MERCREDI,27,JUIN,2018,POULE,20h,Serbie,Brésil,6446000
16,2018-06-28,JEUDI,28,JUIN,2018,POULE,20h,Angleterre,Belgique,6935000
17,2018-06-30,SAMEDI,30,JUIN,2018,HUITIÈMES DE FINALE,16h,France,Argentine,13595000
18,2018-06-30,SAMEDI,30,JUIN,2018,HUITIÈMES DE FINALE,2oh,Uruguay,Portugal,7152000
19,2018-07-01,DIMANCHE,01,JUILLET,2018,HUITIÈMES DE FINALE,16h,Espagne,Russie,1468000
20,2018-07-01,DIMANCHE,01,JUILLET,2018,HUITIÈMES DE FINALE,2oh,Croatie,Danemark,7598000
21,2018-07-02,LUNDI,02,JUILLET,2018,HUITIÈMES DE FINALE,20h,Belgique,Japon,8018000
22,2018-07-03,MARDI,03,JUILLET,2018,HUITIÈMES DE FINALE,20h,Colombie,Angleterre,7714000
23,2018-07-06,VENDREDI,06,JUILLET,2018,QUARTS DE FINALE,16h,Uruguay,France,12880000
24,2018-07-06,VENDREDI,06,JUILLET,2018,QUARTS DE FINALE,20h,Brésil,Belgique,10305000
25,2018-07-07,SAMEDI,07,JUILLET,2018,QUARTS DE FINALE,20h,Russie,Croatie,7365000
26,2018-07-10,MARDI,10,JUILLET,2018,DEMI-FINALE,20h,France,Belgique,20178000
27,2018-07-11,MERCREDI,11,JUILLET,2018,DEMI-FINALE,20h,Croatie,Angleterre,12318000
28,2018-07-14,SAMEDI,14,JUILLET,2018,FINALE,16h,Belgique,Angleterre,5590000
29,2018-07-15,DIMANCHE,15,JUILLET,2018,FINALE,17h,France,Croatie,19340000

In [7]:
game_ratings_2022_df

,date,day_of_week,day,month,year,game_type,hour,team_1,team_2,ratings
0,2022-11-20,DIMANCHE,20,NOVEMBRE,2022,POULE,17h,Qatar,Équateur,5131000
1,2022-11-21,LUNDI,21,NOVEMBRE,2022,POULE,20h,États-Unis,Pays de Galles,3976000
2,2022-11-22,MARDI,22,NOVEMBRE,2022,POULE,20h,FRANCE,Australie,13109000
3,2022-11-23,MERCREDI,23,NOVEMBRE,2022,POULE,20h,Belgique,Canada,5430000
4,2022-11-24,JEUDI,24,NOVEMBRE,2022,POULE,20h,Brésil,Serbie,5873000
5,2022-11-25,VENDREDI,25,NOVEMBRE,2022,POULE,20h,Angleterre,États-Unis,4920000
6,2022-11-26,SAMEDI,26,NOVEMBRE,2022,POULE,17h,FRANCE,Danemark,11590000
7,2022-11-26,SAMEDI,26,NOVEMBRE,2022,POULE,20h,Argentine,Mexique,5742000
8,2022-11-27,DIMANCHE,27,NOVEMBRE,2022,POULE,14h,Belgique,Maroc,3918000
9,2022-11-27,DIMANCHE,27,NOVEMBRE,2022,POULE,20h,Espagne,Allemagne,7478000
10,2022-11-28,LUNDI,28,NOVEMBRE,2022,POULE,20h,Portugal,Uruguay,5770000
11,2022-11-29,MARDI,29,NOVEMBRE,2022,POULE,20h,Pays de Galles,Angleterre,4459000
12,2022-11-30,MERCREDI,30,NOVEMBRE,2022,POULE,16h,Tunisie,FRANCE,8838000
13,2022-11-30,MERCREDI,30,NOVEMBRE,2022,POULE,20h,Pologne,Argentine,5554000
14,2022-12-01,JEUDI,1er,DECEMBRE,2022,POULE,20h,Costa Rica,Allemagne,5538000
15,2022-12-02,VENDREDI,02,DECEMBRE,2022,POULE,20h,Cameroun,Brésil,5557000
16,2022-12-03,SAMEDI,03,DECEMBRE,2022,HUITIÈMES DE FINALE,20h,Argentine,Australie,6028000
17,2022-12-04,DIMANCHE,04,DECEMBRE,2022,HUITIÈMES DE FINALE,16h,FRANCE,Pologne,14324000
18,2022-12-04,DIMANCHE,04,DECEMBRE,2022,HUITIÈMES DE FINALE,20h,Angleterre,Sénégal,7023000
19,2022-12-05,LUNDI,05,DECEMBRE,2022,HUITIÈMES DE FINALE,20h,Brésil,Corée du Sud,5901000
20,2022-12-06,MARDI,06,DECEMBRE,2022,HUITIÈMES DE FINALE,20h,Portugal,Suisse,5840000
21,2022-12-09,VENDREDI,09,DECEMBRE,2022,QUARTS DE FINALE,20h,Pays-Bas,Argentine,7573000
22,2022-12-10,SAMEDI,10,DECEMBRE,2022,QUARTS DE FINALE,16h,Maroc,Portugal,7471000
23,2022-12-10,SAMEDI,10,DECEMBRE,2022,QUARTS DE FINALE,20h,Angleterre,France,17724000

## France games

In [8]:
game_ratings_2018_df.loc[
    (game_ratings_2018_df.team_1 == "France")
    | (game_ratings_2018_df.team_2 == "France")
]

,date,day_of_week,day,month,year,game_type,hour,team_1,team_2,ratings
2,2018-06-16,SAMEDI,16,JUIN,2018,POULE,12h,France,Australie,12590000
8,2018-06-21,JEUDI,21,JUIN,2018,POULE,17h,France,Pérou,10720000
13,2018-06-26,MARDI,26,JUIN,2018,POULE,16h,Danemark,France,8670000
17,2018-06-30,SAMEDI,30,JUIN,2018,HUITIÈMES DE FINALE,16h,France,Argentine,13595000
23,2018-07-06,VENDREDI,06,JUILLET,2018,QUARTS DE FINALE,16h,Uruguay,France,12880000
26,2018-07-10,MARDI,10,JUILLET,2018,DEMI-FINALE,20h,France,Belgique,20178000
29,2018-07-15,DIMANCHE,15,JUILLET,2018,FINALE,17h,France,Croatie,19340000

In [9]:
game_ratings_2022_df.loc[
    (game_ratings_2022_df.team_1 == "FRANCE")
    | (game_ratings_2022_df.team_2 == "FRANCE")
]

,date,day_of_week,day,month,year,game_type,hour,team_1,team_2,ratings
2,2022-11-22,MARDI,22,NOVEMBRE,2022,POULE,20h,FRANCE,Australie,13109000
6,2022-11-26,SAMEDI,26,NOVEMBRE,2022,POULE,17h,FRANCE,Danemark,11590000
12,2022-11-30,MERCREDI,30,NOVEMBRE,2022,POULE,16h,Tunisie,FRANCE,8838000
17,2022-12-04,DIMANCHE,04,DECEMBRE,2022,HUITIÈMES DE FINALE,16h,FRANCE,Pologne,14324000